import type { BuildingDef } from './schema';

/**
 * v0 building roster (GAME_DESIGN §6): starters, era buildings, one unique
 * per civ and eight wonders. Effects are flat `yields` only (plus optional
 * flat city defense) — percentage modifiers are a post-v0 system (so civ
 * trait texts stay display-only in v0). Wonders are
 * unique worldwide; the engine refunds production for a second copy.
 */
export const BUILDINGS: BuildingDef[] = [
  {
    id: 'palace',
    name: 'Palace',
    era: 'ancient',
    cost: 1,
    maintenance: 0,
    yields: { food: 0, production: 2, gold: 3, science: 2, culture: 1 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 4,
  },
  {
    id: 'monument',
    name: 'Monument',
    era: 'ancient',
    cost: 60,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 1, culture: 2 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
  },
  {
    id: 'granary',
    name: 'Granary',
    era: 'ancient',
    cost: 70,
    maintenance: 1,
    yields: { food: 2, production: 0, gold: 0, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'pottery',
  },
  {
    id: 'barracks',
    name: 'Barracks',
    era: 'ancient',
    cost: 75,
    maintenance: 1,
    yields: { food: 0, production: 1, gold: 0, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'bronze_working',
  },
  {
    id: 'library',
    name: 'Library',
    era: 'ancient',
    cost: 90,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 2, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'writing',
  },
  {
    id: 'temple',
    name: 'Temple',
    era: 'ancient',
    cost: 90,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 0, culture: 3 },
    isWonder: false,
    amenityPoints: 1,
    defenseStrength: 0,
    requiresTechId: 'mysticism',
  },
  {
    id: 'walls',
    name: 'Walls',
    era: 'ancient',
    cost: 80,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 6,
    requiresTechId: 'masonry',
  },
  {
    id: 'market',
    name: 'Market',
    era: 'medieval',
    cost: 100,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 3, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'currency',
  },
  {
    id: 'amphitheater',
    name: 'Amphitheater',
    era: 'medieval',
    cost: 100,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 0, culture: 3 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'drama',
  },
  {
    id: 'aqueduct',
    name: 'Aqueduct',
    era: 'medieval',
    cost: 130,
    maintenance: 1,
    yields: { food: 3, production: 0, gold: 0, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'engineering',
  },
  {
    id: 'workshop',
    name: 'Workshop',
    era: 'medieval',
    cost: 110,
    maintenance: 1,
    yields: { food: 0, production: 3, gold: 0, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'engineering',
  },
  {
    id: 'castle',
    name: 'Castle',
    era: 'medieval',
    cost: 150,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 0, culture: 1 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 10,
    requiresTechId: 'chivalry',
  },
  {
    id: 'university',
    name: 'University',
    era: 'medieval',
    cost: 160,
    maintenance: 2,
    yields: { food: 0, production: 0, gold: 0, science: 4, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'education',
  },
  {
    id: 'bank',
    name: 'Bank',
    era: 'renaissance',
    cost: 180,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 4, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'banking',
  },
  {
    id: 'museum',
    name: 'Museum',
    era: 'renaissance',
    cost: 200,
    maintenance: 2,
    yields: { food: 0, production: 0, gold: 0, science: 1, culture: 4 },
    isWonder: false,
    amenityPoints: 1,
    defenseStrength: 0,
    requiresTechId: 'architecture',
  },
  // --- civ uniques ---
  {
    id: 'forum',
    name: 'Forum',
    era: 'medieval',
    cost: 90,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 3, science: 1, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'currency',
    uniqueToCivId: 'rome',
  },
  {
    id: 'mastaba',
    name: 'Mastaba',
    era: 'ancient',
    cost: 85,
    maintenance: 1,
    yields: { food: 0, production: 1, gold: 1, science: 0, culture: 1 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'masonry',
    uniqueToCivId: 'egypt',
  },
  {
    id: 'acropolis',
    name: 'Acropolis',
    era: 'medieval',
    cost: 110,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 1, culture: 3 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 4,
    requiresTechId: 'drama',
    uniqueToCivId: 'greece',
  },
  {
    id: 'stave_church',
    name: 'Stave Church',
    era: 'medieval',
    cost: 120,
    maintenance: 1,
    yields: { food: 0, production: 1, gold: 0, science: 0, culture: 2 },
    isWonder: false,
    amenityPoints: 1,
    defenseStrength: 0,
    requiresTechId: 'theology',
    uniqueToCivId: 'norse',
  },
  {
    id: 'ordu',
    name: 'Ordu',
    era: 'medieval',
    cost: 130,
    maintenance: 1,
    yields: { food: 0, production: 2, gold: 1, science: 0, culture: 0 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 4,
    requiresTechId: 'chivalry',
    uniqueToCivId: 'mongolia',
  },
  {
    id: 'shi',
    name: 'Shi Hall',
    era: 'medieval',
    cost: 140,
    maintenance: 1,
    yields: { food: 0, production: 0, gold: 0, science: 3, culture: 1 },
    isWonder: false,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'education',
    uniqueToCivId: 'china',
  },
  // --- wonders (one per world) ---
  {
    id: 'stonehenge',
    name: 'Stonehenge',
    era: 'ancient',
    cost: 150,
    maintenance: 0,
    yields: { food: 0, production: 0, gold: 0, science: 0, culture: 3 },
    isWonder: true,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'mysticism',
  },
  {
    id: 'colossus',
    name: 'Colossus',
    era: 'ancient',
    cost: 170,
    maintenance: 0,
    yields: { food: 0, production: 0, gold: 4, science: 0, culture: 0 },
    isWonder: true,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'bronze_working',
  },
  {
    id: 'pyramids',
    name: 'Pyramids',
    era: 'ancient',
    cost: 180,
    maintenance: 0,
    yields: { food: 0, production: 2, gold: 0, science: 0, culture: 1 },
    isWonder: true,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'masonry',
  },
  {
    id: 'great_library',
    name: 'Great Library',
    era: 'ancient',
    cost: 200,
    maintenance: 0,
    yields: { food: 0, production: 0, gold: 0, science: 3, culture: 1 },
    isWonder: true,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'writing',
  },
  {
    id: 'angkor_wat',
    name: 'Angkor Wat',
    era: 'medieval',
    cost: 290,
    maintenance: 0,
    yields: { food: 3, production: 1, gold: 0, science: 0, culture: 0 },
    isWonder: true,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'the_wheel',
  },
  {
    id: 'hagia_sophia',
    name: 'Hagia Sophia',
    era: 'medieval',
    cost: 280,
    maintenance: 0,
    yields: { food: 2, production: 0, gold: 0, science: 0, culture: 2 },
    isWonder: true,
    amenityPoints: 1,
    defenseStrength: 0,
    requiresTechId: 'engineering',
  },
  {
    id: 'machu_picchu',
    name: 'Machu Picchu',
    era: 'medieval',
    cost: 300,
    maintenance: 0,
    yields: { food: 0, production: 0, gold: 3, science: 0, culture: 2 },
    isWonder: true,
    amenityPoints: 0,
    defenseStrength: 0,
    requiresTechId: 'currency',
  },
  {
    id: 'notre_dame',
    name: 'Notre-Dame',
    era: 'renaissance',
    cost: 320,
    maintenance: 0,
    yields: { food: 0, production: 0, gold: 0, science: 0, culture: 3 },
    isWonder: true,
    amenityPoints: 2,
    defenseStrength: 0,
    requiresTechId: 'architecture',
  },
];
