import type { CivDef } from './schema';

/** Six civs with first-pass trait concepts (see GAME_DESIGN.md §5). Balance TBD. */
export const CIVS: CivDef[] = [
  {
    id: 'rome',
    name: 'Rome',
    leaderName: 'Augustus',
    color: '#a03030',
    traitName: 'All Roads Home',
    traitDescription: '+15% production toward buildings in all cities.',
    personality: { aggression: 0.7, expansionism: 0.8, scienceFocus: 0.5, defensiveness: 0.5 },
    uniqueUnitId: 'legion',
    uniqueBuildingId: 'forum',
    cityNames: ['Roma', 'Ostia', 'Antium', 'Cumae', 'Neapolis', 'Ravenna', 'Arretium', 'Mediolanum', 'Pompeii', 'Brundisium'],
  },
  {
    id: 'egypt',
    name: 'Egypt',
    leaderName: 'Hatshepsut',
    color: '#c8a24a',
    traitName: 'Gift of the Nile',
    traitDescription: '+1 food on riverside tiles.',
    personality: { aggression: 0.3, expansionism: 0.6, scienceFocus: 0.6, defensiveness: 0.6 },
    uniqueUnitId: 'war_chariot',
    uniqueBuildingId: 'mastaba',
    cityNames: ['Thebes', 'Memphis', 'Heliopolis', 'Elephantine', 'Alexandria', 'Pi-Ramesses', 'Giza', 'Byblos', 'Abydos', 'Asyut'],
  },
  {
    id: 'greece',
    name: 'Greece',
    leaderName: 'Pericles',
    color: '#4a78b8',
    traitName: 'Philosophers',
    traitDescription: '+2 science per city.',
    personality: { aggression: 0.4, expansionism: 0.5, scienceFocus: 0.9, defensiveness: 0.5 },
    uniqueUnitId: 'hoplite',
    uniqueBuildingId: 'acropolis',
    cityNames: ['Athens', 'Sparta', 'Corinth', 'Argos', 'Knossos', 'Rhodes', 'Ephesus', 'Delphi', 'Syracuse', 'Thebes'],
  },
  {
    id: 'norse',
    name: 'Norse',
    leaderName: 'Ragnar',
    color: '#3f6f6a',
    traitName: 'Seafarers',
    traitDescription: 'Cheaper embark; naval units +1 movement.',
    personality: { aggression: 0.8, expansionism: 0.7, scienceFocus: 0.3, defensiveness: 0.3 },
    uniqueUnitId: 'berserker',
    uniqueBuildingId: 'stave_church',
    cityNames: ['Kaupang', 'Birka', 'Trondheim', 'Roskilde', 'Uppsala', 'Tonsberg', 'Sarpsborg', 'Hedeby', 'Jorvik', 'Reykjavik'],
  },
  {
    id: 'mongolia',
    name: 'Mongolia',
    leaderName: 'Genghis Khan',
    color: '#7a4a9a',
    traitName: 'Steppe Raiders',
    traitDescription: 'Cavalry units cost no maintenance.',
    personality: { aggression: 0.95, expansionism: 0.6, scienceFocus: 0.2, defensiveness: 0.2 },
    uniqueUnitId: 'keshik',
    uniqueBuildingId: 'ordu',
    cityNames: ['Karakorum', 'Beshbalik', 'Samarkand', 'Turfan', 'Almarikh', 'Kashgar', 'Ning-hsia', 'Tabriz', 'Hovd', 'Darhan'],
  },
  {
    id: 'china',
    name: 'China',
    leaderName: 'Wu Zetian',
    color: '#b85450',
    traitName: 'Inventive Heritage',
    traitDescription: '+10% science in all cities.',
    personality: { aggression: 0.35, expansionism: 0.55, scienceFocus: 0.85, defensiveness: 0.65 },
    uniqueUnitId: 'chu_ko_nu',
    uniqueBuildingId: 'shi',
    cityNames: ['Beijing', 'Shanghai', 'Guangzhou', 'Xian', 'Chengdu', 'Hangzhou', 'Nanjing', 'Luoyang', 'Wuhan', 'Kaifeng'],
  },
  {
    // Pseudo-civ backing the barbarian camps; never playable or pickable.
    id: 'barbarians',
    name: 'Barbarians',
    leaderName: '—',
    color: '#5a5248',
    traitName: 'Raiders',
    traitDescription: 'Hostile camps that raid nearby civilizations.',
    personality: { aggression: 1, expansionism: 0, scienceFocus: 0, defensiveness: 0.4 },
    cityNames: [],
  },
];
