import type { UnitDef } from './schema';

/**
 * v0 roster (GAME_DESIGN §8): 20 units — settlers/civilians, era progression and one
 * unique unit per playable civ. Uniques are stat variants of a base class —
 * no special rules yet. Water stays impassable for every unit in v0 (no embark).
 */
export const UNITS: UnitDef[] = [
  {
    id: 'settler',
    name: 'Settler',
    unitClass: 'civilian',
    era: 'ancient',
    cost: 80,
    strength: 0,
    rangedStrength: 0,
    range: 0,
    moves: 2,
    maintenance: 0,
    sightRange: 2,
  },
  {
    id: 'scout',
    name: 'Scout',
    unitClass: 'recon',
    era: 'ancient',
    cost: 25,
    strength: 5,
    rangedStrength: 0,
    range: 0,
    moves: 3,
    maintenance: 0.5,
    sightRange: 3,
  },
  {
    id: 'warrior',
    name: 'Warrior',
    unitClass: 'melee',
    era: 'ancient',
    cost: 40,
    strength: 10,
    rangedStrength: 0,
    range: 0,
    moves: 2,
    maintenance: 0.5,
    sightRange: 2,
  },
  {
    id: 'spearman',
    name: 'Spearman',
    unitClass: 'melee',
    era: 'ancient',
    cost: 56,
    strength: 12,
    rangedStrength: 0,
    range: 0,
    moves: 2,
    maintenance: 0.5,
    sightRange: 2,
    requiresTechId: 'bronze_working',
  },
  {
    id: 'archer',
    name: 'Archer',
    unitClass: 'ranged',
    era: 'ancient',
    cost: 60,
    strength: 8,
    rangedStrength: 12,
    range: 2,
    moves: 2,
    maintenance: 0.5,
    sightRange: 2,
    requiresTechId: 'archery',
  },
  {
    id: 'horseman',
    name: 'Horseman',
    unitClass: 'cavalry',
    era: 'ancient',
    cost: 75,
    strength: 14,
    rangedStrength: 0,
    range: 0,
    moves: 4,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'the_wheel',
  },
  {
    id: 'swordsman',
    name: 'Swordsman',
    unitClass: 'melee',
    era: 'ancient',
    cost: 65,
    strength: 16,
    rangedStrength: 0,
    range: 0,
    moves: 2,
    maintenance: 0.5,
    sightRange: 2,
    requiresTechId: 'iron_working',
  },
  {
    id: 'catapult',
    name: 'Catapult',
    unitClass: 'siege',
    era: 'medieval',
    cost: 85,
    strength: 6,
    rangedStrength: 22,
    range: 2,
    moves: 2,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'construction',
  },
  // --- civ uniques: ancient ---
  {
    id: 'hoplite',
    name: 'Hoplite',
    unitClass: 'melee',
    era: 'ancient',
    cost: 56,
    strength: 14,
    rangedStrength: 0,
    range: 0,
    moves: 2,
    maintenance: 0.5,
    sightRange: 2,
    requiresTechId: 'bronze_working',
    uniqueToCivId: 'greece',
  },
  {
    id: 'legion',
    name: 'Legion',
    unitClass: 'melee',
    era: 'ancient',
    cost: 70,
    strength: 18,
    rangedStrength: 0,
    range: 0,
    moves: 2,
    maintenance: 0.5,
    sightRange: 2,
    requiresTechId: 'iron_working',
    uniqueToCivId: 'rome',
  },
  {
    id: 'war_chariot',
    name: 'War Chariot',
    unitClass: 'cavalry',
    era: 'ancient',
    cost: 65,
    strength: 12,
    rangedStrength: 0,
    range: 0,
    moves: 4,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'the_wheel',
    uniqueToCivId: 'egypt',
  },
  // --- medieval ---
  {
    id: 'crossbowman',
    name: 'Crossbowman',
    unitClass: 'ranged',
    era: 'medieval',
    cost: 120,
    strength: 12,
    rangedStrength: 20,
    range: 2,
    moves: 2,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'machinery',
  },
  {
    id: 'knight',
    name: 'Knight',
    unitClass: 'cavalry',
    era: 'medieval',
    cost: 150,
    strength: 24,
    rangedStrength: 0,
    range: 0,
    moves: 4,
    maintenance: 1.5,
    sightRange: 2,
    requiresTechId: 'chivalry',
  },
  {
    id: 'trebuchet',
    name: 'Trebuchet',
    unitClass: 'siege',
    era: 'renaissance',
    cost: 160,
    strength: 8,
    rangedStrength: 34,
    range: 2,
    moves: 2,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'physics',
  },
  {
    id: 'berserker',
    name: 'Berserker',
    unitClass: 'melee',
    era: 'medieval',
    cost: 90,
    strength: 20,
    rangedStrength: 0,
    range: 0,
    moves: 3,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'feudalism',
    uniqueToCivId: 'norse',
  },
  {
    id: 'keshik',
    name: 'Keshik',
    unitClass: 'cavalry',
    era: 'medieval',
    cost: 140,
    strength: 22,
    rangedStrength: 0,
    range: 0,
    moves: 5,
    maintenance: 1.5,
    sightRange: 2,
    requiresTechId: 'chivalry',
    uniqueToCivId: 'mongolia',
  },
  {
    id: 'chu_ko_nu',
    name: 'Chu-Ko-Nu',
    unitClass: 'ranged',
    era: 'medieval',
    cost: 110,
    strength: 12,
    rangedStrength: 18,
    range: 2,
    moves: 2,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'machinery',
    uniqueToCivId: 'china',
  },
  // --- renaissance ---
  {
    id: 'musketman',
    name: 'Musketman',
    unitClass: 'melee',
    era: 'renaissance',
    cost: 200,
    strength: 34,
    rangedStrength: 0,
    range: 0,
    moves: 2,
    maintenance: 1,
    sightRange: 2,
    requiresTechId: 'gunpowder',
  },
  {
    id: 'lancer',
    name: 'Lancer',
    unitClass: 'cavalry',
    era: 'renaissance',
    cost: 220,
    strength: 28,
    rangedStrength: 0,
    range: 0,
    moves: 4,
    maintenance: 1.5,
    sightRange: 2,
    requiresTechId: 'metallurgy',
  },
  {
    id: 'cannon',
    name: 'Cannon',
    unitClass: 'siege',
    era: 'renaissance',
    cost: 230,
    strength: 10,
    rangedStrength: 44,
    range: 2,
    moves: 2,
    maintenance: 1.5,
    sightRange: 2,
    requiresTechId: 'metallurgy',
  },
];
